# Generated by Django 3.2.8 on 2022-02-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220228_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_title',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
