# Generated by Django 3.2.8 on 2022-03-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_rename_is_member_userprofile_is_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_sponsor',
        ),
    ]
