# Generated by Django 3.2.8 on 2022-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiplevel',
            name='level',
            field=models.CharField(choices=[('GO', 'Gold Level'), ('SI', 'Silver Level'), ('BR', 'Bronze Level')], default='BR', max_length=6),
        ),
    ]
