# Generated by Django 3.2.8 on 2022-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20220130_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='sku',
        ),
    ]
