# Generated by Django 3.2.8 on 2022-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_auto_20220205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
