# Generated by Django 3.2.8 on 2022-03-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20220312_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_name',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'free'), ('Supporter', 'sup')], default='Free', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
