# Generated by Django 3.2.8 on 2022-03-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_auto_20220312_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='stripe_plan_id',
        ),
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
