# Generated by Django 3.2.8 on 2022-02-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_memberprofile_userprofile'),
        ('donations', '0003_donation_gift_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile'),
        ),
    ]
