# Generated by Django 3.2.8 on 2022-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_selectors',
            field=models.CharField(blank=True, choices=[('5', '£5'), ('10', '£10'), ('15', '£15'), ('25', '£25'), ('50', '£50')], max_length=5, null=True),
        ),
    ]
