# Generated by Django 3.2.8 on 2022-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20220223_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_custom',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_total',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
