# Generated by Django 3.2.8 on 2022-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20220223_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
