# Generated by Django 3.2.8 on 2022-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donation_donation_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
