# Generated by Django 3.2.8 on 2022-03-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20220301_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_custom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_selectors',
            field=models.DecimalField(blank=True, choices=[('5', '£5'), ('10', '£10'), ('15', '£15'), ('25', '£25'), ('50', '£50')], decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
