# Generated by Django 3.2.8 on 2022-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20220303_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_selectors',
            field=models.CharField(blank=True, choices=[('5', '£5'), ('10', '£10'), ('15', '£15'), ('25', '£25'), ('50', '£50')], max_length=6, null=True),
        ),
    ]
