# Generated by Django 3.2.8 on 2022-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20220304_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_total',
            field=models.DecimalField(choices=[('5', '£5'), ('10', '£10'), ('15', '£15'), ('25', '£25'), ('30', '£30')], decimal_places=2, max_digits=5),
        ),
    ]
