# Generated by Django 3.2.8 on 2022-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0023_alter_donation_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
